DSET-3658 Cross-team query support
scalyr/scalyr-grafana-datasource-plugin pull request #116
Opened 2023-05-08 21:19 UTC by dlobue

First pass at adding MVP cross-team support to grafana datasource.

DSET-3658

2023-05-10 13:05 UTC, jmakar-scalyr commented on pkg/plugin/plugin.go
> +	AccountEmails       *[]string `json:"accountEmails"`
Slices (ie `[]<type>`) are reference types so you can assign nil to them inherently
```
	var a []int = []int{1, 2, 3}
	var b []int = []int{}
	var c []int = nil
```

Better to have the AccountEmails type to be just `[]string`

2023-05-10 13:15 UTC, jmakar-scalyr requested changes
Looks good, just a minor type adjustment to fix

A brief blurb and example screenshots in the README.md would be helpful.  Also good to add a note about this in the CHANGELOG.md as well.

2023-05-11 00:01 UTC, dlobue commented
@jmakar-scalyr all requested changes have been made!

2023-05-11 14:06 UTC, jmakar-scalyr approved these changes
Looks great!

2023-05-11 16:15 UTC, merged